# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-drug-formulary
canonical: http://hl7.org/fhir/us/davinci-drug-formulary
name: Formulary
title: DaVinci Payer Data Exchange (PDex) US Drug Formulary
status: active
version: 2.0.1
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: phx  # <<< The value must be the code for the workgroup
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: STU 2

publisher:
  name: HL7 International / Pharmacy
  url: http://www.hl7.org/Special/committees/medication
  email: pharmacy@lists.HL7.org
description: DaVinci Payer Data Exchange (PDex) US Drug Formulary, Release 2.0.1 - US Realm STU"
license: CC0-1.0
dependencies:
#  hl7.fhir.us.core: 4.0.0
  hl7.fhir.us.davinci-pdex-plan-net: 1.1.0
  hl7.fhir.us.davinci-hrex: 1.0.0
parameters:
  show-inherited-invariants: false
  default-jurisdiction: true
  default-publisher: true
  default-version: true
  default-contact: true
  apply-jurisdiction: false
  apply-publisher: false
  apply-version: false
  apply-contact: false
  
  jira-code: davinci-df
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
jurisdiction: urn:iso:std:iso:3166#US
# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# comment out in sushi v1.3.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Specification:
    Conformance Expectations     : use_cases_and_overview.html#conformance-expectations
    Use Cases                    : use_cases_and_overview.html#use-cases
    Access Methods               : use_cases_and_overview.html#access-methods
    Formulary Structure          : use_cases_and_overview.html#formulary-structure
    Bulk Data                    : use_cases_and_overview.html#bulk-data
    Searching Formulary Drugs    : use_cases_and_overview.html#searching-formulary-drugs
    Additional Guidance          : use_cases_and_overview.html#additional-guidance
    Anticipated Client Queries: queries.html
  FHIR Artifacts:
    Profiles            : artifacts.html#3
    Extensions          : artifacts.html#4
    Search Parameters   : search_parameters.html
    Terminology         : artifacts.html#5
    Capability Statement: CapabilityStatement-usdf-server.html
    Examples            : artifacts.html#7
  Downloads: downloads.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
  Change Notes: change_notes.html


pages:
  index.md:
    title: Home
  credits.md: 
    title: Credits
  use_cases_and_overview.md:
    title: Use Cases and Overview
  search_parameters.md:
    title: Search Parameters
  queries.md:
    title: Queries
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Downloads
  change_notes.md:
    title: Change Notes
  ImplementationGuide-hl7.fhir.us.davinci-drug-formulary.md:
    title: US Drug Formulary ImplementationGuide Resource

resources:
  CapabilityStatement/usdf-server:
    name: US Drug Formulary Server Capability Statement
    