# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-drug-formulary
canonical: http://hl7.org/fhir/us/davinci-drug-formulary
name: Formulary
title: DaVinci Payer Data Exchange (PDex) US Drug Formulary | STU2 Ballot
status: draft
version: 1.2.0
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: STU 2 Ballot

publisher:
  name: HL7 Pharmacy Working Group
  url: http://www.hl7.org/Special/committees/medication
  email: pharmacy@lists.HL7.org
description: Da Vinci Payer Data Exchange (PDex) US Drug Formulary (STU2 ballot)
license: CC0-1.0
dependencies:
  hl7.fhir.us.core: 4.0.0   # updated from 3.1.1 on 8/30/21
  hl7.fhir.us.davinci-pdex-plan-net: 1.0.0
parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  jira-code: davinci-df
  path-expansion-params: '../../exp-params.json'  #path is relative to [base]/fsh-generated/resources
jurisdiction: urn:iso:std:iso:3166#US
# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# comment out in sushi v1.3.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Specification:
    Use Cases                    : use_cases_and_overview.html
    Formulary Structure          : use_cases_and_overview.html#formulary-structure
    Searching Formulary Drugs    : use_cases_and_overview.html#searching-formulary-drugs
    Access Methods               : use_cases_and_overview.html#access-methods
    Additional Guidance          : use_cases_and_overview.html#additional-guidance
    Anticipated Client Queries: queries.html
  FHIR Artifacts:
    Profiles            : artifacts.html#3
    Extensions          : artifacts.html#4
    Search Parameters   : search_parameters.html
    Terminology         : artifacts.html#5
    Capability Statement: CapabilityStatement-usdf-server.html
    Examples            : artifacts.html#7
  Downloads: downloads.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
  Change Notes: change_notes.html


pages:
  index.md:
    title: Home
  credits.md: 
    title: Credits
  use_cases_and_overview.md:
    title: Use Cases and Overview
  search_parameters.md:
    title: Search Parameters
  queries.md:
    title: Queries
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Downloads
  change_notes.md:
    title: Change Notes

resources:
  CapabilityStatement/usdf-server:
    name: US Drug Formulary Server Capability Statement
    