# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-drug-formulary
canonical: http://hl7.org/fhir/us/davinci-drug-formulary
name: Formulary
title: DaVinci Payer Data Exchange (PDex) US Drug Formulary
status: draft
version: 1.0.1
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: CI Build
publisher:
  name: HL7 Pharmacy Working Group
  url: http://www.hl7.org/Special/committees/medication/
  email: pharmacy@lists.HL7.org
description: Da Vinci Payer Data Exchange (PDex) US Drug Formulary STU 1.0.1 (Pre-1.1.0)
license: CC0-1.0
dependencies:
  hl7.fhir.us.core: 3.1.1   # updated from 3.1.0 on 9/23/20
parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  jira-code: davinci-df
jurisdiction: urn:iso:std:iso:3166#US
# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# comment out in sushi v1.3.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Specification:
    Use Cases                    : use_cases_and_overview.html
    Formulary Structure          : use_cases_and_overview.html#formulary-structure
    Access Methods               : use_cases_and_overview.html#access-methods
    Additional Guidance          : use_cases_and_overview.html#additional-guidance
    Anticipated Client Queries: queries.html
  FHIR Artifacts:
    Profiles            : artifacts.html#3
    Extensions          : artifacts.html#4
    Search Parameters   : search_parameters.html
    Terminology         : artifacts.html#5
    Capability Statement: CapabilityStatement-usdf-server.html
    Examples            : artifacts.html#7
  Downloads: downloads.html
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
  


pages:
  index.md:
    title: Home
  credits.md: 
    title: Credits
  use_cases_and_overview.md:
    title: Use Cases and Overview
  search_parameters.md:
    title: Search Parameters
  queries.md:
    title: Queries
  artifacts.html:
    title: Artifacts Summary
  downloads.md:
    title: Downloads


resources:
  List/covplanV1002:
    name: Pre STU 2 - Coverage Plan V1002
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3001:
    name: Pre STU 2 - Coverage Plan V3001
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3002:
    name: Pre STU 2 - Coverage Plan V3002
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3004t:
    name: Pre STU 2 - Coverage Plan V3004t
    description: BluePreferred PPO HSA Silver $3,000
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  MedicationKnowledge/cmsip9:
    name: Pre STU 2 - Formulary Drug cmsip9
    description: Doxepin HCl 5 % Topical Cream
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/formularydrugV1002:
    name: Pre STU 2 - Formulary Drug V1002
    description: Percocet 5 MG / 325 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/FormularyDrugV3001:
    name: Pre STU 2 - Formulary Drug V3001
    description: Percocet 5 MG / 325 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/FormularyDrugV3002:
    name: Pre STU 2 - Formulary Drug V3002
    description: Tylenol Extra Strength 500 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  CapabilityStatement/usdf-server:
    name: US Drug Formulary Server Capability Statement

