# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-drug-formulary
canonical: http://hl7.org/fhir/us/davinci-drug-formulary
name: Formulary
title: DaVinci Payer Data Exchange (PDex) US Drug Formulary
status: draft
version: 1.0.1
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: CI Build
publisher:
  name: HL7 Pharmacy Working Group
  url: http://www.hl7.org/Special/committees/medication/
  email: pharmacy@lists.HL7.org
description: Da Vinci Payer Data Exchange (PDex) US Drug Formulary STU 1.0.1
license: CC0-1.0
dependencies:
  hl7.fhir.us.core: 3.1.1   # updated from 3.1.0 on 9/23/20
parameters:
  show-inherited-invariants: false
  apply-jurisdiction: true
  apply-publisher: true
  jira-code: davinci-df
jurisdiction: urn:iso:std:iso:3166#US
# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# comment out in sushi v1.3.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  FHIR Artifacts:
    Profiles            : artifacts.html#3
    Extensions          : artifacts.html#6
    Search Parameters   : 5_search_parameters.html
    Terminology         : artifacts.html#5
    Capability Statement: CapabilityStatement-usdf-server.html
  Examples      : artifacts.html#7
  Downloads     : downloads.html
  History       : http://hl7.org/fhir/us/davinci-drug-formulary/history.html


resources:
  List/covplanV1002:
    name: Coverage Plan V1002
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3001:
    name: Coverage Plan V3001
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3002:
    name: Coverage Plan V3002
    description: Sample Gold Health Plan
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  List/CoveragePlanV3004t:
    name: Coverage Plan V3004t
    description: BluePreferred PPO HSA Silver $3,000
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-CoveragePlan
  MedicationKnowledge/cmsip9:
    name: Formulary Drug cmsip9
    description: Doxepin HCl 5 % Topical Cream
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/formularydrugV1002:
    name: Formulary Drug V1002
    description: Percocet 5 MG / 325 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/FormularyDrugV3001:
    name: Formulary Drug V3001
    description: Percocet 5 MG / 325 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug
  MedicationKnowledge/FormularyDrugV3002:
    name: Formulary Drug V3002
    description: Tylenol Extra Strength 500 MG Oral Tablet
    exampleCanonical: http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyDrug

